name: 10k 10q
input: ib_solutions/solutions/fs/Instabase Drive/Marketplace apps/10k 10q/input/
binary: ib_solutions/solutions/fs/Instabase Drive/Marketplace apps/10k 10q/10k10q_final_flow.ibflowbin
flow_path: ib_solutions/solutions/fs/Instabase Drive/Marketplace apps/10k 10q/flow/10k10q.ibflow
git_repo: bookish-umbrella
git_owner: IByatharthVardan
branch: main
git_token: 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
ib_token: SCjErWKhSf2Y1FJwF6BshmnqGHhV0W
ib_base_api: https://instabase.com/api/v1/drives/
ib_base: https://instabase.com/api/v1/
ib_path: yatharthVardan/testing_automation_framework/fs/Instabase Drive/files/
ib_environment: instabase.com







